Fix share option being displayed erroneously
nextcloud/files_rightclick pull request #118
Opened 2021-08-09 23:26 UTC by Pytal

Fix #117

2021-08-10 04:08 UTC, nickvergessen requested changes

2021-08-10 04:08 UTC, nickvergessen commented on js/files.js
>                  addNewOption('Share', 'shared', t(appName, 'Share ' + (currentFile.attr('data-type') === 'dir' ? 'folder' : 'file')), function () {
```suggestion
                addNewOption('Share', 'shared', (currentFile.attr('data-type') === 'dir' ? t(appName, 'Share folder') : t(appName, 'Share file')), function () {
```

2021-08-11 00:13 UTC, Pytal commented on js/files.js
>                  addNewOption('Share', 'shared', t(appName, 'Share ' + (currentFile.attr('data-type') === 'dir' ? 'folder' : 'file')), function () {
Commited :)

2021-08-11 06:46 UTC, juliushaertl approved these changes

2021-08-11 06:57 UTC, merged

2021-08-11 06:57 UTC, juliushaertl commented
/backport to stable22

2021-08-11 06:57 UTC, juliushaertl commented
/backport to stable21

2021-08-11 06:57 UTC, juliushaertl commented
/backport to stable20